---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Сайт должен иметь мобильную версию
  - Сайт должен работать в последних версиях браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя
implicit:
  - Сайт должен быть доступен на различных устройствах
